-- ============================================================
-- Agent-X v2 — Project + Account Content Planning System
-- Run this in Supabase SQL Editor after v1.6_FULL_SETUP.sql
-- ============================================================

-- 1) PROJECT ACCOUNTS (each project = niche, has multiple brand accounts)
create table if not exists public.project_accounts (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,                           -- e.g. "AI Tool Daily"
  handle text not null,                         -- e.g. @aitool_daily
  platforms jsonb not null default '["instagram","tiktok","youtube_shorts"]'::jsonb,
  niche text not null,
  status text not null default 'needs_setup' check (status in ('needs_setup','architecting','strategizing','ready','paused')),
  avatar_emoji text default '🤖',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists accounts_project_idx on public.project_accounts(project_id, status);
create index if not exists accounts_user_idx on public.project_accounts(user_id, status);
alter table public.project_accounts enable row level security;
drop policy if exists "own accounts" on public.project_accounts;
create policy "own accounts" on public.project_accounts for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- 2) ACCOUNT DOCUMENTS (business plan, brand guidelines, tone, rules etc. — markdown, generated by agents)
create table if not exists public.account_documents (
  id uuid primary key default gen_random_uuid(),
  account_id uuid not null references public.project_accounts(id) on delete cascade,
  doc_type text not null check (doc_type in ('business_plan','brand_guidelines','tone_guide','visual_rules','content_rules')),
  content text not null,                      -- full markdown content
  agent text not null default 'architect',    -- which agent wrote it
  version int not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (account_id, doc_type)
);
create index if not exists docs_account_idx on public.account_documents(account_id);
alter table public.account_documents enable row level security;
drop policy if exists "own account docs" on public.account_documents;
create policy "own account docs" on public.account_documents for all
  using (exists (select 1 from public.project_accounts a where a.id = account_documents.account_id and a.user_id = auth.uid()))
  with check (exists (select 1 from public.project_accounts a where a.id = account_documents.account_id and a.user_id = auth.uid()));

-- 3) ACCOUNT POSTS (planned reels/carousels/images with all assets + hashtags)
create table if not exists public.account_posts (
  id uuid primary key default gen_random_uuid(),
  account_id uuid not null references public.project_accounts(id) on delete cascade,
  post_type text not null check (post_type in ('reel','carousel','image','short')),
  title text not null,
  hook text,
  script text,                                  -- for reels/shorts
  caption text not null,
  visual_prompt text,
  hashtags text[] not null default '{}',
  duration_seconds int default 30,
  scheduled_at timestamptz,
  status text not null default 'planned' check (status in ('planned','drafted','approved','scheduled','published','rejected')),
  created_by_agent text not null default 'strategist',
  metadata jsonb not null default '{}'::jsonb, -- style, beat count, music mood etc.
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists posts_account_idx on public.account_posts(account_id, status, created_at desc);
alter table public.account_posts enable row level security;
drop policy if exists "own account posts" on public.account_posts;
create policy "own account posts" on public.account_posts for all
  using (exists (select 1 from public.project_accounts a where a.id = account_posts.account_id and a.user_id = auth.uid()))
  with check (exists (select 1 from public.project_accounts a where a.id = account_posts.account_id and a.user_id = auth.uid()));

-- 4) Helper: auto-update updated_at
create or replace function public.touch_updated_at() returns trigger as $$
begin new.updated_at = now(); return new; end; $$ language plpgsql;
drop trigger if exists trg_touch_accounts on public.project_accounts;
create trigger trg_touch_accounts before update on public.project_accounts
  for each row execute function public.touch_updated_at();
drop trigger if exists trg_touch_docs on public.account_documents;
create trigger trg_touch_docs before update on public.account_documents
  for each row execute function public.touch_updated_at();
drop trigger if exists trg_touch_posts on public.account_posts;
create trigger trg_touch_posts before update on public.account_posts
  for each row execute function public.touch_updated_at();

-- 5) Verify
select 'v2 project system ready' as status,
  (select count(*) from public.projects) as projects,
  (select count(*) from public.project_accounts) as accounts,
  (select count(*) from public.account_documents) as documents,
  (select count(*) from public.account_posts) as posts;
